### PR TITLE
Update javarosa v2.12.1

### PR DESCRIPTION
**Pull request by ukanga**
#### What has been done to verify that this works as intended?

Running all http://github.com/xlsform/pyxform tests with the generated jar
file, no failures were reported.

#### Why is this the best possible solution? Were any other approaches considered?

Tried using class `org.javarosa.core.model.actions.Action` but it cannot be
instantiated.

#### Are there any risks to merging this code? If so, what are they?

Yes, Actions may not be validated any more. Should they be validated?

### CODE REVIEW

**Review by yanokwa — APPROVED** [review]
I looked at https://opendatakit.github.io/xforms-spec/#actions and created an example of setting a dynamic value after form load here [action.xml.zip](https://github.com/opendatakit/validate/files/2637712/action.xml.zip)

With master, both of these lines work
* `<setvalue event="xforms-ready" ref="/action/now" value="now()" />`
* `<setvalue event="xforms-ready-broken" ref="/action/now" value="now()" />`

With this PR, the second one fails validation. This seems like an improvement.

Additionally, while I don't understand all the implications of the removal of `org.javarosa.core.model.Action` merging this PR seems very low risk. 

Tagging @ggalmazor for visibility.

**Comment by yanokwa** [comment]
@ukanga Should I do a release of Validate?

**Comment by ukanga** [comment]
@yanokwa Please do. I want to do a release of pyxform this week and having this be part of it would be ideal.

**Comment by yanokwa** [comment]
Release is out at https://github.com/opendatakit/validate/releases/tag/v1.10.3.

**Pull request merged**
