### PR TITLE
Use JavaRosa 2.6.0.

### PR DESCRIPTION
**Pull request by lognaturel**

### CODE REVIEW

**Comment by yanokwa** [comment]
Did you do a quick validation to see if this works with updated forms?

**Comment by lognaturel** [comment]
Yes! I used [round-test.xml.txt](https://github.com/opendatakit/validate/files/1435066/round-test.xml.txt) which has the new round variant added by @iowerx. Apologies for not writing that in the description -- I'm lost without a PR template!

**Comment by yanokwa** [comment]
If only there was a PR for a PR template ;)

**Comment by lognaturel** [comment]
Ohhhhh, totally missed that. Thanks for the nudge.

**Review by yanokwa — APPROVED** [review]

**Pull request merged**
